# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: myrepo/springboot-helm-chart-example
  tag: 1.0.0
  pullPolicy: Always

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

# Enable istio
istio:
  enabled: true
  gateway: main-gw.istio-system.svc.cluster.local
  meshTlsPolicy: DISABLE
  ingress:
    fanout:
      create: false
      baseUrl: ""
      host: 
    subdomain:
      create: true
      host: springboot-helm-chart-example.example.com

# Canary deployment
canary:
  create: false
  replicaCount: 0
  # stable and canary weights in percentage
  stableWeight: 90
  canaryWeight: 10
  image:
    repository: myrepo/springboot-helm-chart-example
    tag: 1.0.1
    pullPolicy: Always

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

rbac:
  create: true

serviceAccount:
  create: true

# Create kubernetes secrets
useExistingSecret: false

# Enable Azure Managed Pod Identity
azureManagedIdentity: true
  
## Azure Key Vault
azureKeyVault:
  enabled: false
  host: https://springboot-example.vault.azure.net

## Environment Variables
environment:
  var1: value1
  var2: value2
